// konsider-api-types-2.0
// Generated from FastAPI OpenAPI by scripts/export_openapi.py. Do not edit.
export interface components {
  schemas: {
    "AggregationPolicyReferenceResponse": { "policy_id": string; "policy_version": string; "method": "TOP_N_MEAN" | "BOTTOM_N_MEAN" | "ALL_VALID_MEAN"; "n": number | null }
    "AssessmentReasonResponse": { "code": string; "severity": "INFO" | "WARNING" | "BLOCKER"; "effect": "NONE" | "ADVISORY" | "COUNTRY_EXCLUDED" | "RANKING_FALLBACK" | "NOT_EVALUATED" }
    "AssessmentsV2Response": { "coverage": components["schemas"]["CoverageAssessmentV2Response"]; "locality": components["schemas"]["ResponseLocalityAssessmentV2Response"]; "profile": components["schemas"]["ProfileAssessmentResponse"]; "opportunity": components["schemas"]["OpportunityAssessmentV2Response"]; "feasibility"?: components["schemas"]["TfcAssessmentV2Response"] | null }
    "CatalogCriterionV2Response": { "id": string; "display_name": string; "historical_names": Array<string>; "category": string; "description": string; "direction": "higher_is_better" | "lower_is_better"; "raw_unit": string; "interpretation": string; "caveats": Array<string>; "quality_limitations": Array<string>; "ready": boolean; "default_enabled": boolean; "experimental": boolean; "scoring_method_version": string; "coverage": components["schemas"]["CriterionCoverageResponse"]; "scope": components["schemas"]["CriterionScopeResponse"]; "applicability": components["schemas"]["CriterionApplicabilityResponse"]; "sources": Array<components["schemas"]["SourceMetadataResponse"]> }
    "CatalogV2Response": { "api_contract_version"?: string; "release_id": string; "release_schema_version": string; "catalog_schema_version": string; "scoring_method_versions": Array<string>; "coverage_policy_version": string; "stable_universe_id": string; "countries": Array<components["schemas"]["GeographicEntityResponse"]>; "criteria": Array<components["schemas"]["CatalogCriterionV2Response"]>; "preference_presets": Array<components["schemas"]["PreferencePresetResponse"]> }
    "ComparedCountryV2Response": { "country": components["schemas"]["GeographicEntityResponse"]; "rank": number | null; "base_rank": number | null; "final_aggregate": number | null; "coverage_excluded": boolean; "opportunity_excluded": boolean; "assessments": components["schemas"]["CountryAssessmentsV2Response"] }
    "ComparisonCellV2Response": { "criterion_id": string; "outcome": "valid" | "missing" | "stale" | "invalid" | "rejected"; "active_for_ranking": boolean; "reason_codes": Array<string>; "source_lineage_ids": Array<string>; "observation_id": string | null; "score_id": string | null; "contribution": components["schemas"]["ContributionV2Response"] | null; "country": components["schemas"]["GeographicEntityResponse"] }
    "ComparisonCriterionRowV2Response": { "criterion_id": string; "criterion_name": string; "coverage": components["schemas"]["CriterionCoverageResponse"]; "scope": components["schemas"]["CriterionScopeResponse"]; "cells": Array<components["schemas"]["ComparisonCellV2Response"]> }
    "ComparisonV2Response": { "api_contract_version"?: string; "release_id": string; "release_schema_version": string; "catalog_schema_version": string; "scoring_method_versions": Array<string>; "resolved_preference_preset_id": string | null; "normalized_weights": Record<string, number>; "assessments": components["schemas"]["AssessmentsV2Response"]; "requested_country_entity_ids": Array<string>; "countries": Array<components["schemas"]["ComparedCountryV2Response"]>; "criterion_rows": Array<components["schemas"]["ComparisonCriterionRowV2Response"]> }
    "ContributingLocalityResponse": { "locality": components["schemas"]["GeographicEntityResponse"]; "input_score": number; "observation_id": string; "score_id": string }
    "ContributionV2Response": { "criterion_id": string; "criterion_name": string; "source_scope": "COUNTRY" | "LOCALITY"; "result_scope": string; "derivation": "DIRECT" | "AGGREGATED_FROM_LOCALITIES"; "score": number; "normalized_weight": number; "contribution": number; "score_id": string; "derived_evidence_id": string | null; "aggregation_policy": components["schemas"]["AggregationPolicyReferenceResponse"] | null; "locality_universe": components["schemas"]["LocalityUniverseReferenceResponse"] | null; "contributing_localities": Array<components["schemas"]["ContributingLocalityResponse"]>; "observations": Array<components["schemas"]["ObservationEvidenceResponse"]>; "source_lineage_ids": Array<string>; "sources": Array<components["schemas"]["SourceMetadataResponse"]>; "scoring_method_version": string; "observation_method_versions": Array<string>; "quality_flags": Array<string> }
    "CountryAssessmentsV2Response": { "locality": components["schemas"]["CountryLocalityAssessmentResponse"]; "profile": components["schemas"]["ProfileAssessmentResponse"]; "opportunity": components["schemas"]["CountryOpportunityAssessmentV2Response"]; "feasibility"?: components["schemas"]["TfcCountryAssessmentV2Response"] | null }
    "CountryCriterionDetailV2Response": { "criterion": components["schemas"]["CatalogCriterionV2Response"]; "evidence": components["schemas"]["CriterionOutcomeEvidenceResponse"] }
    "CountryDetailsV2Response": { "api_contract_version"?: string; "release_id": string; "release_schema_version": string; "catalog_schema_version": string; "scoring_method_versions": Array<string>; "resolved_preference_preset_id": string | null; "normalized_weights": Record<string, number>; "assessments": components["schemas"]["AssessmentsV2Response"]; "country": components["schemas"]["GeographicEntityResponse"]; "criteria": Array<components["schemas"]["CountryCriterionDetailV2Response"]>; "opportunity_filters": Array<components["schemas"]["OpportunityFilterEvidenceSummaryResponse"]>; "feasibility"?: components["schemas"]["TfcCountryAssessmentV2Response"] | null }
    "CountryLocalityAssessmentResponse": { "status": "NO_ACTIVE_LOCALITY_CRITERIA" | "BELOW_ANALYSIS_THRESHOLD" | "ONE_ACTIVE_LOCALITY_CRITERION" | "COMMON_LOCALITY_AVAILABLE" | "PARTIAL_OVERLAP" | "NO_COMMON_LOCALITY" | "INSUFFICIENT_LOCALITY_EVIDENCE" | "MIXED_COUNTRY_RESULTS"; "eligible_locality_entity_ids": Array<string>; "valid_locality_entity_ids": Array<string>; "contributing_locality_entity_ids": Array<string>; "common_locality_entity_ids": Array<string>; "best_common_locality_entity_id": string | null; "criterion_evidence": Array<components["schemas"]["CriterionLocalityEvidenceResponse"]>; "reasons": Array<components["schemas"]["AssessmentReasonResponse"]> }
    "CountryOpportunityAssessmentV2Response": { "evaluated": boolean; "passes": boolean | null; "filter_evidence": Array<components["schemas"]["OpportunityFilterEvidenceSummaryResponse"]> }
    "CoverageAssessmentV2Response": { "status": "NO_PARTIAL_CRITERIA_ACTIVE" | "FULL_COVERAGE" | "PARTIAL_COMPLETE_CASE" | "COVERAGE_LIMIT_FALLBACK"; "policy_version": string; "active_global_core_criterion_ids": Array<string>; "active_conditional_criterion_ids": Array<string>; "excluded_countries": Array<components["schemas"]["ExcludedCountryV2Response"]>; "reasons": Array<components["schemas"]["AssessmentReasonResponse"]> }
    "CriterionApplicabilityResponse": { "mode": "UNIVERSAL" | "PARAMETERIZED" | "FUTURE_PROFILE_REQUIRED"; "dimensions": Array<string> }
    "CriterionCoverageResponse": { "mode": "GLOBAL_CORE" | "CONDITIONAL_COMPLETE_CASE" | "DIAGNOSTIC_ONLY"; "stable_universe_id": string; "stable_country_count": number; "valid_country_count": number; "minimum_valid_country_count": number; "outcome_counts": components["schemas"]["OutcomeCountsResponse"]; "activation_threshold"?: number | null; "score_range": components["schemas"]["ScoreRangeResponse"]; "source_lineage_ids": Array<string> }
    "CriterionLocalityEvidenceResponse": { "criterion_id": string; "eligible_locality_entity_ids": Array<string>; "valid_locality_entity_ids": Array<string>; "contributing_locality_entity_ids": Array<string> }
    "CriterionOutcomeEvidenceResponse": { "criterion_id": string; "outcome": "valid" | "missing" | "stale" | "invalid" | "rejected"; "active_for_ranking": boolean; "reason_codes": Array<string>; "source_lineage_ids": Array<string>; "observation_id": string | null; "score_id": string | null; "contribution": components["schemas"]["ContributionV2Response"] | null }
    "CriterionScopeResponse": { "evidence_level": "COUNTRY" | "LOCALITY"; "result_level": string; "locality_type": "CITY" | "METRO" | "REGION" | "SERVICE_AREA" | null; "derivation": "DIRECT" | "AGGREGATED_FROM_LOCALITIES"; "locality_universe_id": string | null; "aggregation_policy_id": string | null; "locality_analysis_threshold"?: number | null }
    "EntityReferenceResponse": { "entity_id": string; "entity_type": "COUNTRY" | "CITY" | "METRO" | "REGION" | "SERVICE_AREA" }
    "ErrorBody": { "code": string; "message": string; "details"?: Record<string, unknown>; "request_id"?: string | null }
    "ErrorResponse": { "error": components["schemas"]["ErrorBody"] }
    "ExcludedCountryV2Response": { "country": components["schemas"]["GeographicEntityResponse"]; "final_aggregate"?: null; "criterion_evidence": Array<components["schemas"]["CriterionOutcomeEvidenceResponse"]>; "locality_assessment": components["schemas"]["CountryLocalityAssessmentResponse"]; "reasons": Array<components["schemas"]["AssessmentReasonResponse"]> }
    "GeographicEntityResponse": { "entity_id": string; "entity_type": "COUNTRY" | "CITY" | "METRO" | "REGION" | "SERVICE_AREA"; "display_name": string; "country_codes": Array<string>; "region"?: string | null }
    "HealthV2Response": { "api_contract_version"?: string; "release_id": string; "release_schema_version": string; "catalog_schema_version": string; "scoring_method_versions": Array<string>; "status": string; "country_count": number; "enabled_criterion_count": number; "ready_for_rankings": boolean }
    "LocalityUniverseReferenceResponse": { "locality_universe_id": string; "locality_universe_version": string }
    "ObservationEvidenceResponse": { "observation_id": string; "subject": components["schemas"]["EntityReferenceResponse"]; "value": number; "unit": string; "reference_start": string; "reference_end": string; "source_lineage_id": string; "observation_method_version"?: string | null; "parser_version"?: string | null; "quality_flags": Array<string> }
    "OpportunityAssessmentV2Response": { "status": "NO_FILTERS_ACTIVE" | "FILTERS_APPLIED" | "NO_COUNTRIES_MATCH"; "mode": string; "active_filter_ids": Array<string>; "input_ranked_country_count": number; "passing_country_count": number; "excluded_country_count": number; "excluded_counts_by_state": components["schemas"]["OpportunityExcludedCountsResponse"]; "per_filter": Array<components["schemas"]["OpportunityPerFilterAssessmentV2Response"]>; "excluded_countries": Array<components["schemas"]["OpportunityExcludedCountryV2Response"]>; "opportunity_release_id": string | null; "evidence_policy_version": string | null; "source_bundle_version": string | null; "strict_filter_explanation": string; "no_score_impact": boolean }
    "OpportunityExcludedCountryV2Response": { "country_code": string; "base_rank": number; "exclusion_category": "STRONG_SIGNAL_NOT_ESTABLISHED" | "INSUFFICIENT_EVIDENCE"; "failing_filter_evidence": Array<components["schemas"]["OpportunityFilterEvidenceSummaryResponse"]> }
    "OpportunityExcludedCountsResponse": { "STRONG_SIGNAL_NOT_ESTABLISHED": number; "INSUFFICIENT_EVIDENCE": number }
    "OpportunityFilterCatalogV2Response": { "api_contract_version"?: string; "release_id": string; "release_schema_version": string; "catalog_schema_version": string; "scoring_method_versions": Array<string>; "opportunity_release_id": string | null; "state_contract_version": string | null; "evidence_policy_version": string | null; "source_bundle_version": string | null; "mode": string; "no_score_impact": boolean; "definitions": Array<components["schemas"]["OpportunityFilterDefinitionV2Response"]> }
    "OpportunityFilterCoverageResponse": { "assessable_count": number; "state_counts": components["schemas"]["OpportunityFilterStateCountsResponse"]; "source_dependency_status": "AVAILABLE" | "DEGRADED" | "UNAVAILABLE" }
    "OpportunityFilterDefinitionV2Response": { "id": string; "display_name": string; "compact_label": string | null; "category": "CAREER" | "EDUCATION"; "meaning": string; "limitations": Array<string>; "documentation_ref": string; "coverage": components["schemas"]["OpportunityFilterCoverageResponse"]; "source_vintage": Array<components["schemas"]["OpportunitySourceVintageResponse"]>; "active": boolean; "availability": "STAGED" | "AVAILABLE" | "WITHDRAWN"; "mode": string; "eligibility_state": string; "no_score_impact": boolean }
    "OpportunityFilterEvidenceSummaryResponse": { "filter_id": string; "state": "VERIFIED_STRONG_SIGNAL" | "STRONG_SIGNAL_NOT_ESTABLISHED" | "INSUFFICIENT_EVIDENCE"; "passes": boolean; "confidence_band": "HIGH" | "MEDIUM" | "LOW"; "establishing_route_ids": Array<string>; "reason_codes": Array<string>; "reference_period": string | null; "source_ids": Array<string>; "limitations": Array<string>; "documentation_ref": string }
    "OpportunityFilterSelection": { "mode"?: string; "required_filter_ids"?: Array<string> }
    "OpportunityFilterStateCountsResponse": { "VERIFIED_STRONG_SIGNAL": number; "STRONG_SIGNAL_NOT_ESTABLISHED": number; "INSUFFICIENT_EVIDENCE": number }
    "OpportunityPerFilterAssessmentV2Response": { "filter_id": string; "input_country_count": number; "passing_country_count": number; "state_counts": components["schemas"]["OpportunityFilterStateCountsResponse"] }
    "OpportunitySourceVintageResponse": { "source_id": string; "source_version": string; "publisher": string; "attribution": string }
    "OutcomeCountsResponse": { "valid": number; "missing": number; "stale": number; "invalid": number; "rejected": number }
    "PreferencePresetResponse": { "id": string; "name": string; "description": string; "weights": Record<string, number> }
    "ProfileAssessmentResponse": { "status": string; "evaluated_dimensions": Array<string>; "reasons": Array<components["schemas"]["AssessmentReasonResponse"]> }
    "RankedCountryV2Response": { "rank": number; "base_rank": number; "country": components["schemas"]["GeographicEntityResponse"]; "total_score": number; "contributions": Array<components["schemas"]["ContributionV2Response"]>; "assessments": components["schemas"]["CountryAssessmentsV2Response"] }
    "RankingV2Response": { "api_contract_version"?: string; "release_id": string; "release_schema_version": string; "catalog_schema_version": string; "scoring_method_versions": Array<string>; "resolved_preference_preset_id": string | null; "normalized_weights": Record<string, number>; "assessments": components["schemas"]["AssessmentsV2Response"]; "rankings": Array<components["schemas"]["RankedCountryV2Response"]> }
    "ResponseLocalityAssessmentV2Response": { "status": "NO_ACTIVE_LOCALITY_CRITERIA" | "BELOW_ANALYSIS_THRESHOLD" | "ONE_ACTIVE_LOCALITY_CRITERION" | "COMMON_LOCALITY_AVAILABLE" | "PARTIAL_OVERLAP" | "NO_COMMON_LOCALITY" | "INSUFFICIENT_LOCALITY_EVIDENCE" | "MIXED_COUNTRY_RESULTS"; "policy_version": string; "contributing_criterion_ids": Array<string>; "analysis_triggered_criterion_ids": Array<string>; "below_threshold_criterion_ids": Array<string>; "analysis_thresholds": Record<string, number>; "aggregation_policy_ids": Array<string>; "reasons": Array<components["schemas"]["AssessmentReasonResponse"]> }
    "ScoreRangeResponse": { "minimum": number; "maximum": number }
    "SourceMetadataResponse": { "source_id": string; "role"?: "PRIMARY_OBSERVATION" | "ENTITY_UNIVERSE" | "BOUNDARY" | "AUXILIARY" | "SCORING_INPUT" | null; "publisher"?: string | null; "source_version": string; "dataset_version"?: string | null; "asset_uri"?: string | null; "checksum"?: string | null; "licence_id"?: string | null; "canonical_page_url"?: string | null; "attribution"?: string | null; "reference_period"?: string | null }
    "TfcApplicantContextRequest": { "citizenships"?: Array<string>; "country_of_residence"?: string | null; "age_years"?: number | null; "occupation"?: components["schemas"]["TfcTaxonomyReferenceRequest"] | null; "experience_years"?: number | null; "qualifications"?: Array<components["schemas"]["TfcQualificationRequest"]>; "unknown_fields"?: Array<string> }
    "TfcAssessmentSelectionRequest": { "tfc_ids"?: Array<string>; "mode"?: "ASSESS_ONLY" | "REQUIRE_SUPPORTED_MATCH"; "profile_context"?: components["schemas"]["TfcApplicantContextRequest"] | null; "household_context"?: components["schemas"]["TfcHouseholdContextRequest"] | null; "scenario_context"?: components["schemas"]["TfcScenarioContextRequest"] | null }
    "TfcAssessmentV2Response": { "schema_version": string; "profile_context_status": "NO_PROFILE_CONTEXT" | "PARTIAL_PROFILE_CONTEXT" | "COMPLETE_PROFILE_CONTEXT"; "execution_status": "NO_TFC_SELECTED" | "NOT_EXECUTED_NO_CONTEXT" | "EXECUTED"; "filter_mode": "ASSESS_ONLY" | "REQUIRE_SUPPORTED_MATCH"; "selected_tfc_ids": Array<string>; "input_required_fields": Array<string>; "status_counts": components["schemas"]["TfcStatusCountsV2Response"]; "matched_route_count": number; "metric_result_count": number; "no_change_affinity": boolean; "warnings": Array<components["schemas"]["TfcWarningV2Response"]>; "countries": Array<components["schemas"]["TfcCountryAssessmentV2Response"]>; "profile_context_summary": components["schemas"]["TfcProfileContextSummaryV2Response"]; "snapshot": components["schemas"]["TfcSnapshotMetadataV2Response"] | null }
    "TfcBaseRankingReferenceV2Response": { "release_id": string; "country_count": number; "ordering_checksum": string }
    "TfcCatalogV2Response": { "api_contract_version"?: string; "release_id": string; "release_schema_version": string; "catalog_schema_version": string; "scoring_method_versions": Array<string>; "tfc_release_id": string; "tfc_release_schema_version": string; "candidate_status": string; "activation_authorized": boolean; "available_modes": Array<"ASSESS_ONLY" | "REQUIRE_SUPPORTED_MATCH">; "default_mode": string; "selection_is_explicit": boolean; "persisted_server_side": boolean; "no_score_impact": boolean; "definitions": Array<components["schemas"]["TfcDefinitionV2Response"]>; "field_registry": Array<components["schemas"]["TfcFieldDefinitionV2Response"]> }
    "TfcConditionEvaluationV2Response": { "condition_id": string; "field_ids": Array<string>; "status": "MET" | "UNMET" | "UNKNOWN" | "NOT_APPLICABLE"; "blocking": boolean }
    "TfcCountryAssessmentV2Response": { "country_code": string; "base_rank": number; "filtered_rank"?: number | null; "affinity_score_before": number; "affinity_score_after": number; "no_change_affinity": boolean; "outcomes": Array<components["schemas"]["TfcOutcomeV2Response"]> }
    "TfcDefinitionV2Response": { "id": string; "display_name": string; "original_criterion_ids": Array<string>; "user_question": string; "check_kind": "RULE_ROUTE_MATCH" | "SCENARIO_METRIC"; "supported_profile_boundary": string; "supported_destination_codes": Array<string>; "input_requirements": Array<components["schemas"]["TfcInputRequirementV2Response"]>; "limitations": Array<string>; "filter_capability": "ASSESS_ONLY" | "REQUIRE_SUPPORTED_MATCH_ALLOWED"; "applicable_purposes": Array<"WORK" | "STUDY" | "FAMILY" | "EXPLORATION">; "refresh_cadence": string; "policy_id": string; "policy_version": string; "source_summary": Array<components["schemas"]["TfcSourceSummaryV2Response"]>; "effective_from": string; "stale_after": string; "sort_order": number; "no_score_impact": boolean }
    "TfcDependantRequest": { "role": "DEPENDENT_CHILD" | "STEPCHILD" | "OTHER_DEPENDANT"; "relocating"?: boolean | null; "age_band": "UNDER_18" | "AGE_18_TO_20" | "AGE_21_TO_22" | "AGE_23_TO_25" | "OVER_25" | "UNKNOWN"; "age_years"?: number | null }
    "TfcFieldDefinitionV2Response": { "field_id": string; "data_type": string; "validation": string; "sensitivity": "LOW" | "MODERATE_PERSONAL" | "MODERATE_CONSEQUENTIAL" | "HIGH_PERSONAL" | "HIGH_CONSEQUENTIAL"; "default_retention": "TAB_MEMORY_ONLY" | "NEVER_RETAIN_BY_DEFAULT"; "consumer_tfc_ids": Array<string>; "prompt": string; "help_text": string; "may_be_omitted": boolean; "may_be_stored_locally": boolean }
    "TfcHouseholdContextRequest": { "partner_status"?: "NONE" | "SPOUSE" | "CIVIL_PARTNER" | "UNMARRIED_PARTNER" | "UNKNOWN"; "partner_accompanying"?: boolean | null; "partner_work_intent"?: "WORK" | "STUDY" | "NEITHER" | "UNKNOWN"; "dependants"?: Array<components["schemas"]["TfcDependantRequest"]>; "unknown_fields"?: Array<string> }
    "TfcInputRequirementV2Response": { "field_id": string; "requirement": "ALWAYS_REQUIRED" | "CONDITIONALLY_REQUIRED" | "OPTIONAL_EXPLANATORY"; "when_field_id": string | null; "when_equals": string | number | boolean | null }
    "TfcIntendedStudyRequest": { "institution": components["schemas"]["TfcTaxonomyReferenceRequest"]; "qualification_level": "VOCATIONAL" | "BACHELORS" | "MASTERS" | "DOCTORATE" | "OTHER" | "UNKNOWN"; "field": components["schemas"]["TfcTaxonomyReferenceRequest"]; "duration_months": number; "mode": "IN_PERSON" | "HYBRID" | "ONLINE" | "UNKNOWN"; "completion_date": string; "completion_state": "COMPLETED" | "CURRENT" | "PLANNED" }
    "TfcJobOfferRequest": { "state": "PRESENT" | "ABSENT" | "UNKNOWN"; "role"?: string | null; "employer_region_id"?: string | null; "sponsorship_state"?: "CONFIRMED" | "NOT_CONFIRMED" | "NOT_APPLICABLE" | "UNKNOWN"; "salary"?: components["schemas"]["TfcMoneyRequest"] | null }
    "TfcMetricComponentV2Response": { "component_id": string; "field_id": string; "status": "EVALUATED" | "MISSING" | "INCOMPATIBLE_UNIT"; "contribution_minimum": number | null; "contribution_maximum": number | null; "unit": string }
    "TfcMetricResultV2Response": { "result_type": string; "metric_id": string; "formula_type": string; "value": number | null; "minimum": number; "maximum": number; "unit": string; "currency": string | null; "period": "NONE" | "HOURLY" | "MONTHLY" | "ANNUAL"; "components": Array<components["schemas"]["TfcMetricComponentV2Response"]>; "assumptions": Array<string>; "rounding": Record<string, unknown>; "locality_id": string | null; "source_ids": Array<string>; "effective_from": string; "effective_to": string | null; "evidence_quality": "HIGH" | "MEDIUM" | "LOW" }
    "TfcMoneyRequest": { "amount": number; "currency": string; "period": "HOURLY" | "MONTHLY" | "ANNUAL" }
    "TfcOutcomeV2Response": { "tfc_id": string; "country_code": string; "common_status": "EVALUATED" | "INPUT_REQUIRED" | "DESTINATION_EVIDENCE_INSUFFICIENT" | "UNSUPPORTED" | "NOT_APPLICABLE" | "EVALUATION_ERROR"; "reason_codes": Array<string>; "input_required_fields": Array<string>; "result": components["schemas"]["TfcRouteResultV2Response"] | components["schemas"]["TfcMetricResultV2Response"] | null; "warnings": Array<components["schemas"]["TfcWarningV2Response"]> }
    "TfcProfileContextSummaryV2Response": { "provided_layers": Array<"applicant" | "household" | "scenario">; "unknown_field_ids": Array<string>; "returned_profile_values": boolean; "persisted_server_side": boolean }
    "TfcQualificationRequest": { "level": "SECONDARY" | "VOCATIONAL" | "BACHELORS" | "MASTERS" | "DOCTORATE" | "OTHER" | "UNKNOWN"; "field"?: components["schemas"]["TfcTaxonomyReferenceRequest"] | null; "awarding_country"?: string | null; "institution"?: string | null; "completion_year"?: number | null; "recognition_state"?: "NOT_ASSESSED" | "RECOGNIZED_BY_SOURCE" | "UNRESOLVED" | null }
    "TfcRouteEvaluationV2Response": { "route_id": string; "route_name": string; "jurisdiction_id": string; "classification": "MATCH" | "CONDITIONAL" | "NO_MATCH"; "conditions": Array<components["schemas"]["TfcConditionEvaluationV2Response"]>; "source_ids": Array<string>; "effective_from": string; "effective_to": string | null; "evidence_quality": "HIGH" | "MEDIUM" | "LOW" }
    "TfcRouteResultV2Response": { "result_type": string; "match_classification": "SUPPORTED_ROUTE_MATCH" | "CONDITIONAL_ROUTE_MATCH" | "NO_SUPPORTED_ROUTE_MATCH"; "routes": Array<components["schemas"]["TfcRouteEvaluationV2Response"]>; "matched_route_ids": Array<string>; "route_inventory_complete": boolean; "legal_impossibility_disclaimer": string }
    "TfcScenarioContextRequest": { "purpose"?: "WORK" | "STUDY" | "FAMILY" | "EXPLORATION"; "target_date"?: string | null; "target_country_codes"?: Array<string>; "target_region_ids"?: Array<string>; "target_locality_ids"?: Array<string>; "job_offer"?: components["schemas"]["TfcJobOfferRequest"] | null; "intended_occupation"?: components["schemas"]["TfcTaxonomyReferenceRequest"] | null; "intended_study"?: components["schemas"]["TfcIntendedStudyRequest"] | null; "primary_route_id"?: string | null; "relocation_composition"?: "APPLICANT_ONLY" | "WITH_PARTNER" | "WITH_DEPENDANTS" | "WITH_PARTNER_AND_DEPENDANTS" | "UNKNOWN"; "unknown_fields"?: Array<string> }
    "TfcSnapshotMetadataV2Response": { "snapshot_id": string; "tfc_release_id": string; "policy_versions": Record<string, string>; "source_versions": Record<string, string>; "effective_profile_context_hash": string; "evaluation_date": string; "base_ranking_reference": components["schemas"]["TfcBaseRankingReferenceV2Response"]; "persisted_server_side": boolean }
    "TfcSourceSummaryV2Response": { "source_id": string; "publisher": string; "verified_at": string; "effective_from": string; "effective_to": string | null; "attribution": string }
    "TfcStatusCountsV2Response": { "EVALUATED": number; "INPUT_REQUIRED": number; "DESTINATION_EVIDENCE_INSUFFICIENT": number; "UNSUPPORTED": number; "NOT_APPLICABLE": number; "EVALUATION_ERROR": number }
    "TfcTaxonomyReferenceRequest": { "user_text": string; "taxonomy_id"?: string | null; "taxonomy_version"?: string | null; "code"?: string | null; "mapping_state": "MAPPED" | "UNRESOLVED" | "UNKNOWN" }
    "TfcWarningV2Response": { "code": string; "tfc_id": string | null; "country_code": string | null; "record_ids": Array<string> }
    "V2ComparisonRequest": { "weights"?: Record<string, number> | null; "preference_preset_id"?: string | null; "opportunity_filters"?: components["schemas"]["OpportunityFilterSelection"] | null; "feasibility"?: components["schemas"]["TfcAssessmentSelectionRequest"] | null; "country_codes": Array<string> }
    "V2RankingRequest": { "weights"?: Record<string, number> | null; "preference_preset_id"?: string | null; "opportunity_filters"?: components["schemas"]["OpportunityFilterSelection"] | null; "feasibility"?: components["schemas"]["TfcAssessmentSelectionRequest"] | null; "top_k"?: number }
    "V2WeightSelection": { "weights"?: Record<string, number> | null; "preference_preset_id"?: string | null; "opportunity_filters"?: components["schemas"]["OpportunityFilterSelection"] | null; "feasibility"?: components["schemas"]["TfcAssessmentSelectionRequest"] | null }
  }
}
