// Generated from FastAPI OpenAPI by scripts/export_openapi.py. Do not edit.
export interface components {
  schemas: {
    "CatalogCriterionResponse": { "id": string; "display_name": string; "category": string; "description": string; "direction": string; "raw_unit": string; "interpretation": string; "caveats": Array<string>; "quality_limitations": Array<string>; "ready": boolean; "default_enabled": boolean; "experimental": boolean; "scoring_method_version": string; "enabled": boolean; "coverage_mode": "GLOBAL_CORE" | "CONDITIONAL_COMPLETE_CASE" | "DIAGNOSTIC_ONLY"; "valid_country_count": number; "stable_country_count": number; "coverage_percentage": number; "pcc_activation_threshold": number | null; "missing_country_count": number; "concise_caveat": string | null; "sources": Array<components["schemas"]["CriterionSourceResponse"]> }
    "CatalogResponse": { "release_id": string; "release_schema_version": string; "catalog_schema_version": string; "scoring_method_versions": Array<string>; "countries": Array<components["schemas"]["CountryResponse"]>; "criteria": Array<components["schemas"]["CatalogCriterionResponse"]>; "profiles": Array<components["schemas"]["ProfileResponse"]> }
    "ComparisonCellResponse": { "country_code": string; "availability": "AVAILABLE" | "MISSING" | "STALE" | "INVALID" | "REJECTED"; "message_code": string; "active_for_ranking": boolean; "normalized_score": number | null; "raw_observation": number | null; "raw_unit": string | null; "reference_start": string | null; "reference_end": string | null; "source": components["schemas"]["SourceResponse"]; "reason_codes": Array<string> }
    "ComparisonCountrySummaryResponse": { "country_code": string; "country_name": string; "comparison_data_complete": boolean; "ranking_eligible": boolean; "unavailable_displayed_criterion_count": number; "unavailable_active_criterion_count": number; "aggregate_kind": "FINAL" | "FCC_BASELINE" | "NONE"; "ranking_status": "RANKED" | "NOT_RANKED_ACTIVE_DATA_GAP" | "FCC_BASELINE_ONLY"; "message_code": string; "total_score": number | null; "rank": number | null }
    "ComparisonCriterionRowResponse": { "criterion_id": string; "criterion_name": string; "coverage_mode": "GLOBAL_CORE" | "CONDITIONAL_COMPLETE_CASE" | "DIAGNOSTIC_ONLY"; "experimental": boolean; "cells": Array<components["schemas"]["ComparisonCellResponse"]> }
    "ComparisonRequest": { "weights"?: Record<string, number> | null; "profile_id"?: string | null; "country_codes": Array<string> }
    "ComparisonResponse": { "release_id": string; "release_schema_version": string; "catalog_schema_version": string; "scoring_method_versions": Array<string>; "resolved_profile_id": string | null; "normalized_weights": Record<string, number>; "all_zero_behavior": string; "country_tie_breaker": string; "rounding_tolerance": number; "total_eligible_country_count": number; "returned_result_count": number; "stable_universe_size": number; "eligible_universe_size": number; "excluded_country_count": number; "ranking_coverage_mode": "GLOBAL_CORE" | "CONDITIONAL_COMPLETE_CASE"; "uncertainty_status": "NO_PARTIAL_CRITERIA_ACTIVE" | "COVERAGE_LIMIT_EXCEEDED" | "FULL_COVERAGE" | "BASELINE_TOP_K_EXCLUDED" | "POTENTIALLY_AFFECTED" | "ROBUST_TOP_K"; "coverage_band": "PREFERRED" | "ELEVATED" | "BLOCKED"; "reason_codes": Array<string>; "message_code": string; "active_fcc_ids": Array<string>; "active_pcc_ids": Array<string>; "ignored_pcc": Array<components["schemas"]["IgnoredPccResponse"]>; "robustness_k": number; "kth_eligible_score": number | null; "potential_excluded_entrants": Array<string>; "baseline_top_k_country_codes": Array<string>; "baseline_kth_score": number; "baseline_boundary_tie_count": number; "baseline_returned_result_count": number; "policy_version": string; "policy_thresholds": components["schemas"]["PolicyThresholdsResponse"]; "excluded_countries": Array<components["schemas"]["ExcludedCountryResponse"]>; "requested_country_codes": Array<string>; "comparison_country_count": number; "country_summaries": Array<components["schemas"]["ComparisonCountrySummaryResponse"]>; "criterion_rows": Array<components["schemas"]["ComparisonCriterionRowResponse"]>; "requested_excluded_countries": Array<components["schemas"]["ExcludedCountryResponse"]>; "countries": Array<components["schemas"]["RankedCountryResponse"]> }
    "ContributionResponse": { "criterion_id": string; "criterion_name": string; "score": number; "normalized_weight": number; "contribution": number; "scoring_method_version": string; "caveats": Array<string>; "quality_limitations": Array<string>; "experimental": boolean; "observations": Array<components["schemas"]["ObservationResponse"]>; "source": components["schemas"]["SourceResponse"] }
    "CountryCriterionMetricResponse": { "criterion": components["schemas"]["CriterionResponse"]; "normalized_score": number; "scoring_method_version": string; "transform": string; "direction": string; "input_observation_ids": Array<string>; "observations": Array<components["schemas"]["ObservationResponse"]>; "source": components["schemas"]["SourceResponse"] }
    "CountryMetricResponse": { "release_id": string; "release_schema_version": string; "catalog_schema_version": string; "scoring_method_versions": Array<string>; "country": components["schemas"]["CountryResponse"]; "criteria": Array<components["schemas"]["CountryCriterionMetricResponse"]> }
    "CountryResponse": { "code": string; "display_name": string; "region": string }
    "CriterionResponse": { "id": string; "display_name": string; "category": string; "description": string; "direction": string; "raw_unit": string; "interpretation": string; "caveats": Array<string>; "quality_limitations": Array<string>; "ready": boolean; "default_enabled": boolean; "experimental": boolean; "scoring_method_version": string }
    "CriterionSourceResponse": { "source_id": string; "publisher": string; "source_version": string; "dataset_version": string; "canonical_page_url": string; "attribution": string; "reference_period": string }
    "ErrorBody": { "code": string; "message": string; "details"?: Record<string, unknown>; "request_id"?: string | null }
    "ErrorResponse": { "error": components["schemas"]["ErrorBody"] }
    "ExcludedCountryResponse": { "country_code": string; "country_name": string; "r0_rank": number; "r0_score": number; "baseline_top_k_member": boolean; "non_ready_criteria": Array<components["schemas"]["NonReadyCriterionResponse"]>; "optimistic_upper_bound": number | null; "could_enter_top_k": boolean | null }
    "HealthResponse": { "release_id": string; "release_schema_version": string; "catalog_schema_version": string; "scoring_method_versions": Array<string>; "status": string; "country_count": number; "enabled_criterion_count": number; "ready_for_rankings": boolean }
    "IgnoredPccResponse": { "criterion_id": string; "raw_weight": number; "reason_code": string; "activation_threshold": number }
    "NonReadyCriterionResponse": { "criterion_id": string; "outcome": "missing" | "stale" | "invalid" | "rejected"; "reason_codes": Array<string>; "source_id": string; "source_versions": Record<string, string>; "scoring_method_version": string; "observation_id": string | null }
    "ObservationResponse": { "observation_id": string; "value": number; "unit": string; "reference_start": string; "reference_end": string; "observation_method_version": string; "parser_version": string; "quality_flags": Array<string>; "source_records": Array<components["schemas"]["SourceRecordResponse"]> }
    "PolicyThresholdsResponse": { "stable_universe_id": string; "stable_country_count": number; "pcc_min_valid_country_count": number; "preferred_missing_union_max": number; "hard_missing_union_max": number; "min_eligible_country_count": number; "pcc_activation_raw_weight_min": number; "diagnostic_score_max": number; "rounding_tolerance": number }
    "ProfileResponse": { "id": string; "name": string; "description": string; "weights": Record<string, number> }
    "RankedCountryResponse": { "rank": number; "country_code": string; "country_name": string; "region": string; "total_score": number; "eligible_country_count": number; "contributions": Array<components["schemas"]["ContributionResponse"]>; "strengths": Array<string>; "tradeoffs": Array<string> }
    "RankingRequest": { "weights"?: Record<string, number> | null; "profile_id"?: string | null; "top_k"?: number }
    "RankingResponse": { "release_id": string; "release_schema_version": string; "catalog_schema_version": string; "scoring_method_versions": Array<string>; "resolved_profile_id": string | null; "normalized_weights": Record<string, number>; "all_zero_behavior": string; "country_tie_breaker": string; "rounding_tolerance": number; "total_eligible_country_count": number; "returned_result_count": number; "stable_universe_size": number; "eligible_universe_size": number; "excluded_country_count": number; "ranking_coverage_mode": "GLOBAL_CORE" | "CONDITIONAL_COMPLETE_CASE"; "uncertainty_status": "NO_PARTIAL_CRITERIA_ACTIVE" | "COVERAGE_LIMIT_EXCEEDED" | "FULL_COVERAGE" | "BASELINE_TOP_K_EXCLUDED" | "POTENTIALLY_AFFECTED" | "ROBUST_TOP_K"; "coverage_band": "PREFERRED" | "ELEVATED" | "BLOCKED"; "reason_codes": Array<string>; "message_code": string; "active_fcc_ids": Array<string>; "active_pcc_ids": Array<string>; "ignored_pcc": Array<components["schemas"]["IgnoredPccResponse"]>; "robustness_k": number; "kth_eligible_score": number | null; "potential_excluded_entrants": Array<string>; "baseline_top_k_country_codes": Array<string>; "baseline_kth_score": number; "baseline_boundary_tie_count": number; "baseline_returned_result_count": number; "policy_version": string; "policy_thresholds": components["schemas"]["PolicyThresholdsResponse"]; "excluded_countries": Array<components["schemas"]["ExcludedCountryResponse"]>; "rankings": Array<components["schemas"]["RankedCountryResponse"]> }
    "SourceRecordResponse": { "locator": string; "record_id": string }
    "SourceResponse": { "source_id": string; "publisher": string; "source_version": string; "dataset_version": string; "canonical_page_url": string; "attribution": string }
  }
}
