// Generated from FastAPI OpenAPI by scripts/export_openapi.py. Do not edit.
export interface components {
  schemas: {
    "CatalogCriterionResponse": { "id": string; "display_name": string; "category": string; "description": string; "direction": string; "raw_unit": string; "interpretation": string; "caveats": Array<string>; "quality_limitations": Array<string>; "ready": boolean; "default_enabled": boolean; "experimental": boolean; "scoring_method_version": string; "sources": Array<components["schemas"]["CriterionSourceResponse"]> }
    "CatalogResponse": { "release_id": string; "release_schema_version": string; "catalog_schema_version": string; "scoring_method_versions": Array<string>; "countries": Array<components["schemas"]["CountryResponse"]>; "criteria": Array<components["schemas"]["CatalogCriterionResponse"]>; "profiles": Array<components["schemas"]["ProfileResponse"]> }
    "ComparisonRequest": { "weights"?: Record<string, number> | null; "profile_id"?: string | null; "country_codes": Array<string> }
    "ComparisonResponse": { "release_id": string; "release_schema_version": string; "catalog_schema_version": string; "scoring_method_versions": Array<string>; "resolved_profile_id": string | null; "normalized_weights": Record<string, number>; "all_zero_behavior": string; "country_tie_breaker": string; "rounding_tolerance": number; "total_eligible_country_count": number; "returned_result_count": number; "countries": Array<components["schemas"]["RankedCountryResponse"]> }
    "ContributionResponse": { "criterion_id": string; "criterion_name": string; "score": number; "normalized_weight": number; "contribution": number; "scoring_method_version": string; "caveats": Array<string>; "quality_limitations": Array<string>; "experimental": boolean; "observations": Array<components["schemas"]["ObservationResponse"]>; "source": components["schemas"]["SourceResponse"] }
    "CountryCriterionMetricResponse": { "criterion": components["schemas"]["CriterionResponse"]; "normalized_score": number; "scoring_method_version": string; "transform": string; "direction": string; "input_observation_ids": Array<string>; "observations": Array<components["schemas"]["ObservationResponse"]>; "source": components["schemas"]["SourceResponse"] }
    "CountryMetricResponse": { "release_id": string; "release_schema_version": string; "catalog_schema_version": string; "scoring_method_versions": Array<string>; "country": components["schemas"]["CountryResponse"]; "criteria": Array<components["schemas"]["CountryCriterionMetricResponse"]> }
    "CountryResponse": { "code": string; "display_name": string; "region": string }
    "CriterionResponse": { "id": string; "display_name": string; "category": string; "description": string; "direction": string; "raw_unit": string; "interpretation": string; "caveats": Array<string>; "quality_limitations": Array<string>; "ready": boolean; "default_enabled": boolean; "experimental": boolean; "scoring_method_version": string }
    "CriterionSourceResponse": { "source_id": string; "publisher": string; "source_version": string; "dataset_version": string; "canonical_page_url": string; "attribution": string; "reference_period": string }
    "ErrorBody": { "code": string; "message": string; "details"?: Record<string, unknown>; "request_id"?: string | null }
    "ErrorResponse": { "error": components["schemas"]["ErrorBody"] }
    "HealthResponse": { "release_id": string; "release_schema_version": string; "catalog_schema_version": string; "scoring_method_versions": Array<string>; "status": string; "country_count": number; "enabled_criterion_count": number; "ready_for_rankings": boolean }
    "ObservationResponse": { "observation_id": string; "value": number; "unit": string; "reference_start": string; "reference_end": string; "observation_method_version": string; "parser_version": string; "quality_flags": Array<string>; "source_records": Array<components["schemas"]["SourceRecordResponse"]> }
    "ProfileResponse": { "id": string; "name": string; "description": string; "weights": Record<string, number> }
    "RankedCountryResponse": { "rank": number; "country_code": string; "country_name": string; "region": string; "total_score": number; "contributions": Array<components["schemas"]["ContributionResponse"]>; "strengths": Array<string>; "tradeoffs": Array<string> }
    "RankingRequest": { "weights"?: Record<string, number> | null; "profile_id"?: string | null; "top_k"?: number | null }
    "RankingResponse": { "release_id": string; "release_schema_version": string; "catalog_schema_version": string; "scoring_method_versions": Array<string>; "resolved_profile_id": string | null; "normalized_weights": Record<string, number>; "all_zero_behavior": string; "country_tie_breaker": string; "rounding_tolerance": number; "total_eligible_country_count": number; "returned_result_count": number; "rankings": Array<components["schemas"]["RankedCountryResponse"]> }
    "SourceRecordResponse": { "locator": string; "record_id": string }
    "SourceResponse": { "source_id": string; "publisher": string; "source_version": string; "dataset_version": string; "canonical_page_url": string; "attribution": string }
  }
}
